version: '3'
services:
  zookeeper:
    container_name: kafka-zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka-net

  kafka-broker-1:
    container_name: kafka-broker-1
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
    - kafka-net

  kafka-broker-2:
    container_name: kafka-broker-2
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29093:29093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
    - kafka-net

  message-producer:
    container_name: message-producer
    image: kafka-producer
    depends_on:
      - kafka-broker-1
    environment:
      KAFKA_BROKER_HOSTNAME: kafka-broker-1
      KAFKA_TOPIC: TOPIC_ONE
    ports:
      - 8001:8080
    networks:
    - kafka-net

  # message-consumer:
  #   container_name: message-consumer
  #   image: kafka-consumer
  #   depends_on:
  #     - kafka
  #   environment:
  #     KAFKA_BROKER_HOSTNAME: kafka-broker-1
  #     TOPIC: TOPIC_ONE
  #     GROUP_ID: group_one
  #   networks:
  #   - kafka-net

networks:
  kafka-net:
    name: kafka-net
